name: Create Package

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set type of change
        run: echo "::set-output name=commitMsg::$(git show -s --format=%s)"
      - name: Install Dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Update Version
        run: |
          $commitMsg = $(git show -s --format=%s)
          if [[ $commitMsg -eq patch ]]; then
            echo "it's a patch!"
          fi
          npm --no-git-tag-version version patch -m "Upgrading to %s"
      - name: Pack package
        run: npm pack
      - name: Publish package
        run: |
          echo 'this is where we would publish'
