name: Create Package

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org/"

      - name: Auth to NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Check login
        run: npm whoami

      - name: Install Dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Update Version
        run: |
          npm version ${{ github.event.release.name }} --no-git-tag-version
      - name: Pack package
        run: npm pack
      - name: Publish package
        run: npm publish --access public --verbose
