name: Create Package

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Update Version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          FIRST_WORD=$(echo "$COMMIT_MSG" | awk '{print $1}')
          echo "Last commit message was: $COMMIT_MSG"
          echo "First word was : $FIRST_WORD"
          ALLOWED_VERBS=("major" "minor" "patch")
          IS_ALLOWED=false
          for VERB in "${ALLOWED_VERBS[@]}"; do
            if [[ "$FIRST_WORD" -eq "$VERB" ]]; then
              IS_ALLOWED=true
              break
            fi
          done
          # if [[ "$FIRST_WORD" -eq "patch" ]]; then
          #   echo "it's a patch!"
          # fi
          # if [[ "$FIRST_WORD" -eq "major" ]]; then
          # fi
          if $IS_ALLOWED; then
            npm --no-git-tag-version version $FIRST_WORD -m "Upgrading to %s"
          else
            echo "Failed to specify a valid verb: choose major, minor, or patch"
            exit 1
          fi

          # npm --no-git-tag-version version patch -m "Upgrading to %s"
      - name: Pack package
        run: npm pack
      - name: Publish package
        run: |
          echo 'this is where we would publish'
