name: Create Package

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org/"

      - name: Auth to NPM
        run: npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Install Dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Update Version
        run: |
          npm version ${{ github.event.release.name }} --no-git-tag-version

      - name: Pack package
        run: npm pack

      - name: Publish package
        run: npm publish --access public --verbose
  test:
    needs: [publish]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org/"

      - name: Test Package
        run: |
          npm install -g @smallbatchsolutions/gin
          smallbatch-gin create project testProject
          cd testProject
          npm run start
          npm run test
          cd ..
          smallbatch-gin create library testLibrary
          npm run build
          npm test
          npm start
          npm link
          npx ./test-library-1.0.0.tgz
