name: "PR"

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Pack application
        run: npm pack
      - name: Test application
        run: |
          npx @smallbatchsoftware-gin@1.0.0.tgz create test-project
          cd test-project
          npm start
          npm test
