name: Test Package

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org/"

      - name: Test Package
        run: |
          npm install -g @smallbatchsolutions/gin
          smallbatch-gin create testProject
          cd testProject
          npm run start
          npm run test
